using System.Collections.Generic;

namespace Engine.Models
{
    public static class GameHands
    {
        public static List<Hand> EarlyGameHands;

        static GameHands()
        {
            // 1 is raise
            // 2 is bet
            // 3 is limp
            // 4/5 is fold
            EarlyGameHands = new List<Hand>
            {
                new Hand("AAo",1),
                new Hand("KKo",1),
                new Hand("QQo",1),
                new Hand("JJo",2),
                new Hand("1010o",2),
                new Hand("99o",3),
                new Hand("88o",3),
                new Hand("77o",3),
                new Hand("66o",3),
                new Hand("55o",3),
                new Hand("44o",3),
                new Hand("33o",3),
                new Hand("22o",3),
                new Hand("AKs",1),
                new Hand("AQs",2),
                new Hand("AJs",3),
                new Hand("A10s",3),
                new Hand("A9s",4),
                new Hand("A8s",4),
                new Hand("A7s",4),
                new Hand("A6s",4),
                new Hand("A5s",4),
                new Hand("A4s",4),
                new Hand("A3s",4),
                new Hand("A2s",4),
                new Hand("KQs",3),
                new Hand("KJs",3),
                new Hand("K10s",3),
                new Hand("K9s",4),
                new Hand("K8s",4),
                new Hand("K7s",4),
                new Hand("K6s",4),
                new Hand("K5s",4),
                new Hand("K4s",4),
                new Hand("K3s",4),
                new Hand("K2s",4),
                new Hand("QJs",3),
                new Hand("Q10s",3),
                new Hand("Q9s",4),
                new Hand("Q8s",4),
                new Hand("Q7s",4),
                new Hand("Q6s",4),
                new Hand("Q5s",4),
                new Hand("Q4s",4),
                new Hand("Q3s",4),
                new Hand("Q2s",4),
                new Hand("J10s",3),
                new Hand("J9s",5),
                new Hand("J8s",5),
                new Hand("J7s",5),
                new Hand("J6s",5),
                new Hand("J5s",5),
                new Hand("J4s",5),
                new Hand("J3s",5),
                new Hand("J2s",5),
                new Hand("109s",3),
                new Hand("108s",5),
                new Hand("107s",5),
                new Hand("106s",5),
                new Hand("105s",5),
                new Hand("104s",5),
                new Hand("103s",5),
                new Hand("102s",5),
                new Hand("98s",3),
                new Hand("97s",5),
                new Hand("96s",5),
                new Hand("95s",5),
                new Hand("94s",5),
                new Hand("93s",5),
                new Hand("92s",5),
                new Hand("87s",3),
                new Hand("86s",5),
                new Hand("85s",5),
                new Hand("84s",5),
                new Hand("83s",5),
                new Hand("82s",5),
                new Hand("76s",3),
                new Hand("75s",5),
                new Hand("74s",5),
                new Hand("73s",5),
                new Hand("72s",5),
                new Hand("65s",3),
                new Hand("64s",5),
                new Hand("63s",5),
                new Hand("62s",5),
                new Hand("54s",3),
                new Hand("53s",5),
                new Hand("52s",5),
                new Hand("43s",3),
                new Hand("42s",5),
                new Hand("32s",3),

                new Hand("AKo",1),
                new Hand("AQo",2),
                new Hand("AJo",3),
                new Hand("A10o",3),
                new Hand("A9o",4),
                new Hand("A8o",4),
                new Hand("A7o",4),
                new Hand("A6o",4),
                new Hand("A5o",4),
                new Hand("A4o",4),
                new Hand("A3o",4),
                new Hand("A2o",4),
                new Hand("KQo",3),
                new Hand("KJo",4),
                new Hand("K10o",4),
                new Hand("K9o",4),
                new Hand("K8o",4),
                new Hand("K7o",4),
                new Hand("K6o",4),
                new Hand("K5o",4),
                new Hand("K4o",4),
                new Hand("K3o",4),
                new Hand("K2o",4),
                new Hand("QJo",3),
                new Hand("Q10o",4),
                new Hand("Q9o",4),
                new Hand("Q8o",4),
                new Hand("Q7o",4),
                new Hand("Q6o",4),
                new Hand("Q5o",4),
                new Hand("Q4o",4),
                new Hand("Q3o",4),
                new Hand("Q2o",4),
                new Hand("J10o",4),
                new Hand("J9o",5),
                new Hand("J8o",5),
                new Hand("J7o",5),
                new Hand("J6o",5),
                new Hand("J5o",5),
                new Hand("J4o",5),
                new Hand("J3o",5),
                new Hand("J2o",5),
                new Hand("109o",4),
                new Hand("108o",5),
                new Hand("107o",5),
                new Hand("106o",5),
                new Hand("105o",5),
                new Hand("104o",5),
                new Hand("103o",5),
                new Hand("102o",5),
                new Hand("98o",4),
                new Hand("97o",5),
                new Hand("96o",5),
                new Hand("95o",5),
                new Hand("94o",5),
                new Hand("93o",5),
                new Hand("92o",5),
                new Hand("87o",4),
                new Hand("86o",5),
                new Hand("85o",5),
                new Hand("84o",5),
                new Hand("83o",5),
                new Hand("82o",5),
                new Hand("76o",4),
                new Hand("75o",5),
                new Hand("74o",5),
                new Hand("73o",5),
                new Hand("72o",4),
                new Hand("65o",4),
                new Hand("64o",5),
                new Hand("63o",5),
                new Hand("62o",5),
                new Hand("54o",4),
                new Hand("53o",5),
                new Hand("52o",5),
                new Hand("43o",3),
                new Hand("42o",5),
                new Hand("32o",4),
            };
        }
    }

    public class Hand
    {
        public Hand(string handCode, int rank)
        {
            HandCode = handCode;
            Rank = rank;
        }

        public string HandCode { get; set; }
        public int Rank { get; set; }
    }
}
